### ISSUE TITLE
No Input on Demo Site

### ISSUE THREAD

**Issue by jcthress** [davestaab/f3-name-check#1]
Just submitting the same message I sent you on Slack here - it just says:

"F3 Knoxville Name Check

Pool Boy posted 203 times"

When I go to https://f3-name-check.staabstory.com/

Do I need to do something differently? That's pretty neat it's updating from the Wordpress Website. I'd think we'd want to add (if possible?) Slack info check as lots of guys might get added to Slack but not to the Wordpress site (yes, that's on the workout leader and AO-Q but things happen and we want a failsafe way to do a quick check here).

Appreciate the work you're doing! SYITG!

**Comment by davestaab** [comment]
Hey @jcthress, 

Thanks for the feedback! That's a good idea about slack integration. I'll have to look into that next.

You're part of the early beta you could say so it's not completely functional yet. 😁 Hopefully we'll have the search input up soon and some nice styling!
